all:
  hosts:
    new_static_ip_vm:
      ansible_host: 10.0.3.33
      ansible_user: fenkil
      ansible_become: yes

    docker:
      ansible_host: 10.0.55.10
      ansible_user: fenkil
      ansible_become: yes

