version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 6969:6969 # Whisparr
      - 7878:7878 # Radarr
    volumes:
      - /home/fenkil/pcData/arr-stack:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=fWFpmfBnoXrFQcGemFWWjHrq
      - OPENVPN_PASSWORD=c3AnVBB3qCwn3RMy7qUY32k9
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      #- WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=America/Toronto
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8085
    volumes:
      - /home/fenkil/pcData/arr-stack/qbittorrent:/config
      - /mnt/tn_media/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/fenkil/pcData/arr-stack/jackett/data:/config
      - /home/fenkil/pcData/arr-stack/jackett/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/fenkil/pcData/arr-stack/sonarr/data:/config
      - /mnt/tn_media/TVShows:/tv #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/fenkil/pcData/arr-stack/prowlarr/data:/config
    restart: unless-stopped

  # whisparr:
  #   image: hotio/whisparr:nightly
  #   container_name: whisparr
  #   network_mode: "service:gluetun"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Toronto
  #   volumes:
  #     - /home/fenkil/pcData/arr-stack/whisparr/config:/config
  #     - /home/fenkil/pcData/arr-stack/whisparr/data:/data
  #     - /home/fenkil/pcData/arr-stack/whisparr/downloadclient-downloads:/downloads #optional
  #   restart: unless-stopped

  radarr:
    image: hotio/radarr:nightly
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/fenkil/pcData/arr-stack/radarr/config:/config
      - /home/fenkil/pcData/arr-stack/radarr/data:/data
      - /mnt/tn_media/Movies:/movies #optional
    restart: unless-stopped



    ## as all the services are in the same gluetun network - to connect to qbittorrent, leave localhost and only change the port