---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons


- Main:
    - Promox:
        icon: proxmox.png
        href: https://10.0.5.100:8006
        description: Proxmox.

    - TrueNAS:
        icon: truenas.png
        href: https://10.0.203.171
        description: TrueNAS.
        widget:
          type: truenas
          url: https://10.0.203.171
          username: admin # not required if using api key
          password: # not required if using api key
          enablePools: true # optional, defaults to false
          nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    
    - UptimeKuma:
        icon: uptime-kuma.png
        href: http://10.0.10.50:3001
        description: UptimeKuma.
        widget:
            type: uptimekuma
            key: uk1_3FoU4LhfAm7BNp6AvgG97UK30Jb9_LSIi4iNUMrG
            url: http://10.0.10.50:3001
            slug: statuspageslug
            fields: ["up", "down", "uptime", "incident"]

- Media:
    - Jellyfin-VM:
        icon: jellyfin.png
        href: http://10.0.10.40:8096
        description: Media Jellyfin.
        widget:
          type: jellyfin
          url: http://10.0.10.40:8096
          key: fb8b51f6b2c74b369f1f32135fe0e129
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true

    - Jellyfin2:
        icon: jellyfin.png
        href: http://10.0.3.100:8096
        description: Movies & TV Shows Jellyfin.
        widget:
          type: jellyfin
          url: http://10.0.3.100:8096
          key: ae84feec59824e279cae6f88691a6716
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true

    - Jellyfin-TN:
        icon: jellyfin.png
        href: http://10.0.203.171:8096
        description: Audio Jellyfin.
        widget:
          type: jellyfin
          url: http://10.0.203.171:8096
          key: 80f675566cfe480ea2a95fe3789d1d2c
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Plex:
        icon: plex.png
        href: http://10.0.3.10:32400
        description: Plex.

- Central Containers:
    - Portainer:
        icon: portainer.png
        href: http://10.0.10.20:9000
        description: Portainer.
        widget:
          type: portainer
          url: http://10.0.10.20:9000
          env: 1
          key: ptr_accesskeyaccesskeyaccesskeyaccesskey

    - Gitea:
        icon: gitea.png
        href: http://10.0.10.20:7000
        description: Local Git Server.

- Main Containers:
    - Portainer:
        icon: portainer.png
        href: http://10.0.10.30:9000
        description: Portainer.
        widget:
          type: portainer
          url: http://10.0.10.30:9000
          env: 1
          key: ptr_accesskeyaccesskeyaccesskeyaccesskey
    - FocalBoard:
        icon: focalboard.png
        href: http://10.0.10.30:7000
        description: Focalboard.
    - FreshRSS:
        icon: freshrss.png
        href: http://10.0.10.30:32768
        description: RSS Feed.
        widget:
          type: freshrss
          url: http://10.0.10.30:32768
          username: username
          password: password
    - Gluetun:
        icon: gluetun.png
        href: http://10.0.10.30:6881
        description: VPN service container using Gluetun.
    - qBittorrent:
        icon: qbittorrent.png
        href: http://10.0.10.30:8085
        description: qBittorrent client with web UI.
    - Jackett:
        icon: jackett.png
        href: http://10.0.10.30:9117
        description: Jackett indexer service.
    - Sonarr:
        icon: sonarr.png
        href: http://10.0.10.30:8989
        description: Sonarr TV show manager.
    - Radarr:
        icon: radarr.png
        href: http://10.0.10.30:7878
        description: Radarr Movie show manager.
    - Prowlarr:
        icon: prowlarr.png
        href: http://10.0.10.30:9696
        description: Prowlarr indexer manager.
    - DumbPad:
        icon: pad.png
        href: http://10.0.10.30:3030
        description: DumbPad.
    - Personal-Nextcloud:
        icon: nextcloud.png
        href: http://10.0.10.30:8080
        description: Personal.
    - Work-Nextcloud:
        icon: nextcloud-white.png
        href: http://10.0.10.30:4000
        description: Work.
    - ChangeDetection:
        icon: changedetection-io.png
        href: http://10.0.10.30:5000
        description: ChangeDetection.
    - Wekan:
        icon: wekan.png
        href: http://10.0.10.30:4040
        description: Wekan.
    - PdfDing:
        icon: pdf.png
        href: http://10.0.10.30:8181
        description: PDF document manager.
    - Mealie:
        icon: mealie.png
        href: http://10.0.10.30:4005
        description: Recipe manager and meal planner.
    - Resume Reactive:
        icon: resume.png
        href: http://10.0.10.30:3080/dashboard/resumes
        description: Resume Reactive
    - Portainer:
        icon: portainer.png
        href: http://10.0.10.60:9000
        description: Portainer-60.
        widget:
          type: portainer
          url: http://10.0.10.60:9000
          env: 1
          key: ptr_accesskeyaccesskeyaccesskeyaccesskey

- Syncthing:
    - Syncthing-TN:
        icon: syncthing.png
        href: http://10.0.203.171:20910/#
    - Syncthing-DT:
        icon: syncthing.png
        href: http://localhost:8384
    - Syncthing-devServer:
        icon: syncthing.png
        href: http://10.0.10.70:41847

- TN-Llm-Apps-IP20:
    - Portainer:
        icon: portainer.png
        href: http://10.0.203.20:9000
        description: Portainer.
        widget:
          type: portainer
          url: http://10.0.203.20:9000
          env: 1
          key: ptr_accesskeyaccesskeyaccesskeyaccesskey
    - Whisper:
        icon: ward.png
        href: http://10.0.203.20:7070
        description: Transcriber.
    - VoiceNotes:
        icon: vultr.png
        href: http://10.0.203.20:7080
        description: Transcriber.
    - Syncthing-LLM:
        icon: syncthing.png
        href: http://10.0.203.20:8384/#
    - OpenWebUI:
        icon: open-webui-light.png
        href: http://10.0.203.20:8080
    - n8n:
        icon: n8n.png
        href: http://10.0.203.20:3002

- TN-Docker-Apps-IP30:
    - Portainer:
        icon: portainer.png
        href: http://10.0.203.30:9000
        description: Portainer.
        widget:
          type: portainer
          url: http://10.0.203.30:9000
          env: 1
          key: ptr_accesskeyaccesskeyaccesskeyaccesskey

    - Obsidian:
        icon: obsidian.png
        href: http://10.0.203.30:3000
        description: Obsidian.

- Work-PC-Docker:
    - MarkItDown converter:
        icon: markdown.png
        href: http://10.0.234.16:7000
        description: MarkItDown converter
    - Email analysis:
        icon: email.png
        href: http://10.0.234.16:7003
        description: Email analysis
    - Change control helper:
        icon: changecontrol.png
        href: http://10.0.234.16:7001
        description: Change control helper
    - Quality Event Helper:
        icon: QE.png
        href: http://10.0.234.16:7011
        description: Quality Event Helper
    - Root cause analysis:
        icon: rootcause.png
        href: http://10.0.234.16:7002
        description: Root cause analysis
    - SOP reviewer:
        icon: sop.png
        href: http://10.0.234.16:7004
        description: SOP reviewer
    - WorkSimpleRAG:
        icon: worksimplerag.png
        href: http://10.0.234.16:7005
        description: WorkSimpleRAG
    - WorkVault (document management):
        icon: workvault.png
        href: http://10.0.234.16:7006
        description: WorkVault (document management)
    - COA Analyzer (certificate analysis):
        icon: coa.png
        href: http://10.0.234.16:7007
        description: COA Analyzer (certificate analysis)
    - Simple Invoice Analyzer:
        icon: invoice.png
        href: http://10.0.234.16:7009
        description: Simple Invoice Analyzer
    - Audit Checklist:
        icon: audit.png
        href: http://10.0.234.16:7010
        description: Audit Checklist
    - Meeting Notes:
        icon: notes.png
        href: http://10.0.234.16:7018
        description: Meeting Notes
    - Resume Builder:
        icon: resume.png
        href: http://10.0.234.16:7019
        description: Resume Builder
    - Language Learning:
        icon: language.png
        href: http://10.0.234.16:7014
        description: Language Learning


# - Hypervisor:
#     - Proxmox:
#         icon: proxmox.svg
#         href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#         description: pve1
#         widget:
#             type: proxmox
#             url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#             username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
#             password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
#             node: xing-01
#     - Proxmox:
#         icon: proxmox.svg
#         href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#         description: pve2
#         widget:
#             type: proxmox
#             url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#             username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
#             password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
#             node: xing-02
#     - Proxmox:
#         icon: proxmox.svg
#         href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#         description: pve2
#         widget:
#             type: proxmox
#             url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#             username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
#             password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
#             node: xing-03
#     - Proxmox:
#         icon: proxmox.svg
#         href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#         description: pve4
#         widget:
#             type: proxmox
#             url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
#             username:  "{{HOMEPAGE_VAR_PROXMOX_USER}}"
#             password:  "{{HOMEPAGE_VAR_PROXMOX_API_KEY}}"
#             node: storinator
# - Containers:
#     - Rancher:
#         icon: rancher.svg
#         href: "{{HOMEPAGE_VAR_RACNHER_URL}}"
#         description: k8s
#     - Longhorn:
#         icon: longhorn.svg
#         href: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
#         description: k8s storage
#     - Portainer:
#         icon: portainer.svg
#         href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
#         description: docker
#         widget:
#             type: portainer
#             url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
#             env: 2
#             key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
# - DNS:
#     - Pi-Hole1:
#         icon: pi-hole.svg
#         href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
#         description: quasar
#         widget:
#             type: pihole
#             url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
#             key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
#     - Pi-Hole2:
#         icon: pi-hole.svg
#         href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
#         description: blazar
#         widget:
#             type: pihole
#             url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
#             key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
#     - Pi-Hole3:
#         icon: pi-hole.svg
#         href: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}"
#         description: electron
#         widget:
#             type: pihole
#             url: "{{HOMEPAGE_VAR_PIHOLE_URL_3}}"
#             key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_3}}"
# - Network:
#     - UniFi:
#         icon: unifi.svg
#         href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
#         description: network
#         widget:
#             type: unifi
#             url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
#             username:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
#             password:  "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
#     - Uptime Kuma:
#         icon: uptime-kuma.svg
#         href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
#         description: internal
#         widget:
#             type: uptimekuma
#             url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
#             slug: home
#     - Uptime Robot:
#         icon: https://play-lh.googleusercontent.com/cUrv0t00FYQ1GKLuOTvv8qjo1lSDjqZC16IOp3Fb6ijew6Br5m4o16HhDp0GBu_Bw8Y=w240-h480-rw
#         href: https://uptimerobot.com/dashboard
#         description: external
#         widget:
#             type: uptimerobot
#             url: https://api.uptimerobot.com
#             key: "{{HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY}}"
# - Storage:
#     - TrueNAS:
#         icon: truenas.svg
#         href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#         description: scale
#         widget:
#             type: truenas
#             url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
#             key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
#     - MinIO:
#         icon: minio.svg
#         href: "{{HOMEPAGE_VAR_MINIO_URL}}"
#         description: object storage
# - Media:
#     - Plex:
#         icon: plex.svg
#         href: "{{HOMEPAGE_VAR_PLEX_URL}}"
#         description: media server
#         widget:
#             type: plex
#             url: "{{HOMEPAGE_VAR_PLEX_URL}}"
#             key: "{{HOMEPAGE_VAR_PLEX_API_TOKEN}}"
#     - Tautulli:
#         icon: tautulli.svg
#         href: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
#         description: plex stats
#         widget:
#             type: tautulli
#             url: "{{HOMEPAGE_VAR_TAUTULLI_URL}}"
#             key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"
#     - HDHomerun:
#         icon: hdhomerun.png
#         href: "{{HOMEPAGE_VAR_HDHOMERUN_URL}}"
#         description: flex 4k
#         widget:
#             type: hdhomerun
#             url: "{{HOMEPAGE_VAR_HDHOMERUN_URL}}"
# - Remote Access:
#     - PiKVM:
#         icon: https://avatars.githubusercontent.com/u/41749659?s=200&v=4
#         href: "{{HOMEPAGE_VAR_PIKVM_URL}}"
#         description: remote kvm
#     - IPMI:
#         icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
#         href: "{{HOMEPAGE_VAR_IPMI_1_URL}}"
#         description: storinator
#     - IPMI:
#         icon: https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg
#         href: "{{HOMEPAGE_VAR_IPMI_2_URL}}"
#         description: hl15
#     - Netboot:
#         icon: https://netboot.xyz/img/nbxyz-laptop.gif
#         href: "{{HOMEPAGE_VAR_NETBOOT_URL}}"
#         description: network boot utility
#     - Tripp Lite:
#         icon: https://upload.wikimedia.org/wikipedia/commons/f/f9/Tripp_Lite_logo.svg
#         href: "{{HOMEPAGE_VAR_UPS_1_URL}}"
#         description: 1500
#     - Eaton:
#         icon: https://cdn11.bigcommerce.com/s-fg272t4iw0/images/stencil/1280x1280/products/2549/2802/C-12556__63907.1557814942.jpg?c=2
#         href: "{{HOMEPAGE_VAR_UPS_2_URL}}"
#         description: 5p
# - Home Automation:
#     - Home Assistant:
#         icon: home-assistant.svg
#         href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
#         description: home
#         widget:
#             type: homeassistant
#             url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
#             key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"
#     - UniFi:
#         icon: https://play-lh.googleusercontent.com/DmgQvSdocOrGr0D0rxSBE9sqh23Fw3ck3BgKRN788cZnOKgcZlcEAFRYwmUbp6vMTVI
#         href: "{{HOMEPAGE_VAR_UNIFI_PROTECT_URL}}"
#         description: protect
#     - Scryped:
#         icon: https://www.scrypted.app/images/web_hi_res_512.png
#         href: "{{HOMEPAGE_VAR_SCRYPTED_URL}}"
#         description: mgmt console
#     - Broadlink Control:
#         icon: https://nwzimg.wezhan.net/contents/sitefiles3606/18030899/images/5430245.png
#         href: "{{HOMEPAGE_VAR_BROADLINK_CONTROL_URL}}"
#         description: light control
# - Other:
#     - GitLab:
#         icon: gitlab.svg
#         href: https://gitlab.com
#         description: source code
#     - GitHub:
#         icon: github.svg
#         href: https://github.com
#         description: source code
#     - Shlink:
#         icon: https://shlink.io/images/shlink-logo-blue.svg
#         href: "{{HOMEPAGE_VAR_SHLINK_URL}}"
#         description: dashboard

