version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 9117:9117 # Jackett
      - 9696:9696 # Prowlarr
      - 6969:6969 # Whisparr
      - 3033:3033 # yt-dlp
      - 9900:3000 # firefox
      - 9901:3001 # firefox

    volumes:
      - /home/fenkil/pcData/vpnstack/gluten:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=fWFpmfBnoXrFQcGemFWWjHrq
      - OPENVPN_PASSWORD=c3AnVBB3qCwn3RMy7qUY32k9
      # Wireguard:
      #- WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      #- WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=America/Toronto
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8085
    volumes:
      - /home/fenkil/pcData/vpnstack/qbittorrent:/config
      - /gkp/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /home/fenkil/pcData/vpnstack/jackett/data:/config
      - /home/fenkil/pcData/vpnstack/jackett/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/fenkil/pcData/vpnstack/prowlarr/data:/config
    restart: unless-stopped

  whisparr:
    image: hotio/whisparr:nightly
    container_name: whisparr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/fenkil/pcData/vpnstack/whisparr/config:/config
      - /home/fenkil/pcData/vpnstack/whisparr/data:/data
      - /home/fenkil/pcData/vpnstack/whisparr/downloadclient-downloads:/downloads #optional
    restart: unless-stopped


  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui
    container_name: yt-dlp-webui
    network_mode: "service:gluetun"
    volumes:
      - /gkp/downloads:/downloads # replace <your dir> with a directory on your host system
    restart: unless-stopped

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - FIREFOX_CLI=https://www.linuxserver.io/ #optional
    network_mode: "service:gluetun"
    volumes:
      - /home/fenkil/pcData/vpnstack/firefox/config:/config
    shm_size: "1gb"
    restart: unless-stopped

    ## as all the services are in the same gluetun network - to connect to qbittorrent, leave localhost and only change the port